### ISSUE TITLE
Using HTML tags in keys

### ISSUE THREAD

**Issue by madeInLagny** [i18next/i18next-gitbook#100]
I have been trying to find how to incorporate html tags in keys, using interpolation. However, I could not get this to work. 

`"key": "<span class='{{class}}'>Organisor</span> subscription"`

`i18next.t('key',{ class: 'blue' });`

This returns

`[object, object]`

What is the recommended way to manage HTML tags in keys ?

**Comment by jamuhl** [comment]
Did you read / try: https://www.i18next.com/translation-function/interpolation#unescape

**Comment by madeInLagny** [comment]
Hello, yes I did. I tried all options. The best I could get is this:
` "premiumParticipant": "Abonnement {{startSpan}} participant Premium {{endSpan}}"`

`i18next.t("pricing:premiumParticipant", {
                      startSpan: "<span class='nephritis'>",
                      endSpan: "</span>",
                      interpolation: { escapeValue: false }
                    })`
This returns:

`ABONNEMENT <SPAN CLASS='NEPHRITIS'> PARTICIPANT PREMIUM </SPAN>`

Which is obviously not what I am looking for. Any hints on how I should handle this ?
Thanks

**Comment by jamuhl** [comment]
`"premiumParticipant": "Abonnement <SPAN CLASS='NEPHRITIS'> participant Premium </SPAN>"` i18next.t('premiumParticipant') will return what you expect...it does not escape the tags...it's your UI framework doing that...

**Comment by madeInLagny** [comment]
Thank you for your reply. I will use an innerHtml method to solve the
problem.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 30 sept. 2019 à 09:38, Jan Mühlemann <notifications@github.com> a
écrit :
