### ISSUE TITLE
PHP port

### ISSUE THREAD

**Issue by pkly** [i18next/i18next-gitbook#102]
I've made a port of i18next, and I'd appriciate it if it could be added to the page. All the tests in the repo are passing, you can try it out yourself, it's on composer and all that.

Link to the repo https://github.com/pkly/i18next-php

I'm planning to port over the more useful plugins and add implementations for them as time allows and they could be useful, so.

As for why: the other PHP versions seemed kinda meh to me, I'm aware of another port of it being made currently, but it's targetting a specific framework - something I've wanted to avoid.

**Comment by jamuhl** [comment]
Can you provide a PR for adding it?

**Comment by pkly** [comment]
Sure: #103

**Comment by jamuhl** [comment]
merged and should be published
