### ISSUE TITLE
Use i18next-node-mongo-backend instead of i18next-node-mongodb-backend because several issues

### ISSUE THREAD

**Issue by laodemalfatih** [i18next/i18next-gitbook#115]
I offer a library that I wrote instead of the library [i18next-node-mongodb-backend](https://github.com/gian788/i18next-node-mongodb-backend#readme) for integration with MongoDB. I wrote a new library because there were authentication issues that had not been resolved in the previous library. If you are interested, please visit the [i18next-node-mongo-backend](https://github.com/laodemalfatih/i18next-node-mongo-backend) repository.

**Comment by jamuhl** [comment]
Nice. Feel free to provide a PR adding it to: https://www.i18next.com/overview/plugins-and-utils#backends
