### ISSUE TITLE
Text is being shrinked

### ISSUE THREAD

**Issue by jahicDario** [i18next/i18next-gitbook#123]
If translated string is longer than original one, react shrinks string.

**Comment by jamuhl** [comment]
please provide a sample to reproduce...never experienced that myself

**Comment by adrai** [comment]
@jahicDario wrong repository.
Please create a codesandbox example (like https://codesandbox.io/s/react-i18next-dqnj6) or similar and if it's reproducable create an issue in this repository: https://github.com/i18next/react-i18next
