### ISSUE TITLE
Nesting example suggests JSON, but doesn't use JSON

### ISSUE THREAD

**Issue by lynn** [i18next/i18next-gitbook#130]
The [example for nesting](https://www.i18next.com/translation-function/nesting#passing-options-to-nestings) has a hint reading:

> Make sure the options string is valid JSON and can be parsed using JSON.parse
>
>     'sampleKey': 'test $t(nest2, { "changedVarName": "{{var}}" })'

However, the example right above it does not follow this advice.

```json
{
      "girlsAndBoys": "$t(girls, {'count': {{girls}} }) and {{count}} boy",
      "girlsAndBoys_plural": "$t(girls, {'count': {{girls}} }) and {{count}} boys",
      "girls": "{{count}} girl",
      "girls_plural": "{{count}} girls"
}
```

`{'count': {{girls}} }` is not valid JSON.

**Comment by jamuhl** [comment]
"fixed" was done this way because of the syntax highlighting -> changes it to use `\"` which might confuse some peoples even more - but anyway at least that is correct

**Comment by souvik2805** [comment]
Same issue, But unable to solve

**Comment by adrai** [comment]
please provide a reproducible example
