### ISSUE TITLE
Interpolation does not work without joinArray and returnObjects true

### ISSUE THREAD

**Issue by sonicvision** [i18next/i18next-gitbook#131]
## 🐛 Bug Report
Interpolation does not work if joinArray is not provided when you have an array of strings as value of key

## To Reproduce

```js
 
    "ArrayKey": [
      "Please, transfer {{amount}}, so we can proceed with your investment order.",
      "something",
    ],


const [t] = useTranslation();

const texts = t('ArrayKey', {
                    amount: '11',
                    returnObjects: true,
                  })

```

## Expected behavior
Above I expect the texts to be an array of strings with amount to be replaced by 11. But the same doesn't happen

```js
 [
      "Please, transfer 11, so we can proceed with your investment order.",
      "something",
    ]
```

## Your Environment

- *runtime version*: node v14
- *i18next version*: 19.6.3
- *os*: Mac
- *Using React Hook* Library react-i18next

**Comment by jamuhl** [comment]
do not open issues in the gitbook repo...open them in the i18next repo...https://github.com/i18next/i18next

https://github.com/i18next/i18next/blob/master/test/translator/translator.translate.array.spec.js#L69 --> proofs it works as expected

please provide an issue in the correct repo with codesandbox for reproduction...thanks
