### ISSUE TITLE
Migration guide for up to v19 

### ISSUE THREAD

**Issue by gptt916** [i18next/i18next-gitbook#138]
## 🐛 Bug Report

The migration guide at https://www.i18next.com/misc/migration-guide does not include up to the latest versions (v17-18, 18-19)

## To Reproduce

https://www.i18next.com/misc/migration-guide

## Expected behavior
There should be entries for the latest versions

**Comment by adrai** [comment]
There is nothing to migrate for v18 and v19: https://github.com/i18next/i18next/blob/master/CHANGELOG.md

**Comment by jamuhl** [comment]
v18 -> v19 was "just" a typescript change. Not sure we need to address that extra in the migration guide -> as there is no obvious change in the API

**Comment by gptt916** [comment]
Should there be an entry like 14-> 15 to show there are no api changes as to avoid confusion?

**Comment by jamuhl** [comment]
done
