### ISSUE TITLE
Extended example in "Getting Started" uses deprecated XHR backend

### ISSUE THREAD

**Issue by mogsdad** [i18next/i18next-gitbook#139]
## 🐛 Bug Report

The JSFiddle linked from [getting-started.md line 111](https://github.com/i18next/i18next-gitbook/blame/8b0f2ed5500e759350c800dca41b10b739f97f6b/overview/getting-started.md#L111) uses `i18nextXHRBackend`, which, according to [the backend list](https://www.i18next.com/overview/plugins-and-utils#backends), is deprecated.

## To Reproduce

See the linked JSFiddle: https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html

```
[source code](https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html)
```

## Expected behavior

Since it's part of the documentation for i18next, the provided example should use supported components.

I've forked the example and updated it to use `i18nextHttpBackend` instead.
The documentation can be changed to link to that, instead:

```
[source code](https://jsfiddle.net/Mogsdad/pxdcam51/2#tabs=js,result,html)
```

Alternatively, the original JSFiddle could be updated by `jamuhl`.

## Your Environment

- n/a

**Comment by jamuhl** [comment]
was updated...thank you for reporting...
