### ISSUE TITLE
Need help to "Plurals" for muti-language support

### ISSUE THREAD

**Issue by yanweibj** [i18next/i18next-gitbook#141]
https://www.i18next.com/translation-function/plurals

We have a project that support muti-languages.
And we use 
{
  "keyWithCount": "{{count}} item",
  "keyWithCount_plural": "{{count}} items"
}

It works well for en/fr/de.
count = 1 return "key"
count = 2,3,4...   return "key_plural"
![image](https://user-images.githubusercontent.com/16932498/96681434-d6424480-13a9-11eb-910a-2cc34f588dc8.png)

But for ja/ko/zh-cn/zh-tw.
the code will return "key_0" no matter the count is.
![image](https://user-images.githubusercontent.com/16932498/96681514-f8d45d80-13a9-11eb-85b6-f5ef18d89041.png)

My code is like this:
rules: {{count}} rule
rules_pural: {{count}} rules

For ja/ko/zh-cn/zh-tw,
It will use "rules: {{count}} rule" as it can't find key "rules_0".

Please help to advise how to solve my problem.

**Comment by yanweibj** [comment]
My project will use the same keys in all languages.

**Comment by adrai** [comment]
For these languages there is no singular/plural distinction.
There's only 1 key "rules_0"
This is how the plural roles work in i18next.
So you need to add the key "rules_0" for zh for example and no rules + rules_plural

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals same rule for languages not having pluralforms

**Comment by yanweibj** [comment]
Thank you all.
