### ISSUE TITLE
Django-i18next is not related to i18next

### ISSUE THREAD

**Issue by mjpieters** [i18next/i18next-gitbook#142]
## 🐛 Bug Report

The i18next website lists Django as one of the supported frameworks and includes the Django logo. However, this appears to be a misunderstanding based on the existence of a project named [`django-i18next`](http://pythonhosted.org/django-i18next/). Unfortunately, the only connection between that project and the i18next JavaScript framework is the name. The Django project adds a few small features to the Django i18n support in its templating language, and does not provide any integration with the JS framework. 

## To Reproduce

The i18next project site links to django-i18next in the [_Supported frameworks_ section](https://www.i18next.com/overview/supported-frameworks), and includes the Django logo in the [ecosystem graphic](https://gblobscdn.gitbook.com/assets%2F-L9iS6Wm2hynS5H9Gj7j%2F-L9iS7LlT2W7wFtJH-2n%2F-L9iSBP9U65-bHJBRSDv%2Fi18next-ecosystem.jpg). I did not find any other references to Django on the site, so the `django-i18next` project appears to be the only connection.

However, examining the [project documentation](https://django-i18next.readthedocs.io/) (note: new link, current link you have is broken) and [GitHub repository](https://github.com/barseghyanartur/django-i18next) I found no references to the Javascript library, or, for that matter, any other JS code. The core of the project is a [set of Django template language extensions](https://github.com/barseghyanartur/django-i18next/blob/master/src/i18next/templatetags/i18next.py) that [let you override the current locale selectively or disable translations](https://django-i18next.readthedocs.io/en/0.1.1/#usage), nothing more. 

## Expected behavior

Please remove the mention of Django altogether. The link is confusing and misleading.

**Comment by jamuhl** [comment]
....will do so when time allows

**Comment by jamuhl** [comment]
should be removed...hopefully catched all places
