### ISSUE TITLE
Getting started i18next.init() too complicated for beginners

### ISSUE THREAD

**Issue by 8ctopus** [i18next/i18next-gitbook#163]
## 🚀 Feature Proposal

i18next.init() returns a `Promise` which is a concept that is not easy to grasp for unexperienced developers or coming from other languages that don't have this concept. There is a beginner friendlier way to initialize i18next using `initImmediate: false` which makes it synchronous.

So my proposal is to either add a synchronous example to the getting started or at least mention the `initImmediate` configuration option for those looking for it.

If you find it a good idea, I can prepare a PR.

**Comment by adrai** [comment]
Thank you for the advice, just made some additions to the docs: https://www.i18next.com/overview/getting-started#basic-sample.

`initImmediate: false` is not necessary if passing the resources directly in init, it is only necessary if your backend loads resources sync, like the [i18next-fs-backend](https://github.com/i18next/i18next-fs-backend#if-set-i18next-initimmediate-option-to-false-it-will-load-the-files-synchronously)
https://www.i18next.com/overview/configuration-options#misc
![image](https://user-images.githubusercontent.com/1086194/121496872-29214880-c9db-11eb-94ef-b130593daf5a.png)

**Comment by jamuhl** [comment]
Just a note: doing webdevelopment and coming fron environments not embrassing async processing one should really learn those concepts. web is more or less async by nature.

**Comment by 8ctopus** [comment]
@adrai I like the update, makes it easier to understand for novices.
@jamuhl of course, however your aim as the devs of i18next should be to make it easy to use for everyone whatever their level of programming is.

**Comment by 8ctopus** [comment]
@adrai
`// i18next is only already initialized, because the translation resources are already passed in via init function`

maybe change it to
`// i18next is already initialized, because the translation resources where passed via init function`

**Comment by 8ctopus** [comment]
@adrai `if you are lacy loading the translation resources,` fix `lacy` typo

**Comment by adrai** [comment]
thx, not a native english speaker
