### ISSUE TITLE
Documentation contradicts itself concerning support of json format

### ISSUE THREAD

**Issue by jonathan-wiens** [i18next/i18next-gitbook#165]
## 🐛 Bug Report

[This page](https://www.i18next.com/misc/json-format#json-format) documents what JSON format is supported by i18next. It doesn't contain arrays.
[This page](https://www.i18next.com/translation-function/objects-and-arrays) documents that arrays are supported within the JSON for keys.

## To Reproduce

Not relevant, since it's a documentation error.

## Expected behavior

[The JSON format page](https://www.i18next.com/misc/json-format#json-format) includes arrays as supported format.

## Your Environment

Not relevant, since it's a documentation error.

**Comment by jamuhl** [comment]
The JSON format page does not include the array -> as it is no linguistic part of the format -> simple strings, plurals and context are linguistically needed to form proper translations 

Array and objects are only a technical representation of multiple strings

**Comment by jonathan-wiens** [comment]
Thanks for the answer. I think it would still be helpful to include arrays as an example in the JSON format, even if it has no linguistic impact. When I read "JSON format" I would understand it to be the exact technical JSON format supported by i18next, nothing more.
Reading it as is gives the impression that arrays are not supported, technically.

**Comment by jamuhl** [comment]
I extended the page: https://www.i18next.com/misc/json-format#i-18-next-json-v3
