### ISSUE TITLE
"Supported frameworks" needs cleanup

### ISSUE THREAD

**Issue by igorsantos07** [i18next/i18next-gitbook#166]
## 🐛 Bug Report

Not sure how to better fix this (also because it would need further details from the packages), so I'm opening an issue instead:
- react.js description is a bit redundant
- there are a couple of repeated descriptions that don't help with selecting a lib (e.g. three Vue libs, two PHP libs with the same name + a fork)
- IIRC, Angular and Angular.js are two different-ish things?

Also, capitalization is all over the place:
- all JS frameworks look like JS files, while at least some of those don't really use `.js` as a suffix (React is just React, for instance)
- most abbreviations are in lower case (such as HTTP, PHP, HTML5)
- it seems this is actually a common pattern across multiple pages. However, while here and there it may seem like an oversight, on this page it's a bit jarring for the repetition.

Bonus: is this bug report template really meaningful for a docs repository? :thinking:

**Comment by jamuhl** [comment]
good question - the community can add their packages on those pages - we neither have time to review those nor to test which one is the "best" implementation. Regarding typos or wrong spellings - we're no native English speakers - so PR are welcome to clean that up.
