### ISSUE TITLE
Fallback parsing

### ISSUE THREAD

**Issue by VeronQ** [i18next/i18next-gitbook#168]
## 🐛 Bug Report

Fallback string with the `:` (colon) punctuation mark extracts only parts of it.

## To Reproduce

Use the `i18next.t(keys, options)` function with an undefined key.

```js
i18next.t('Undefined variable: $example')
// Output is: " $example"
```

## Expected behavior

If the key is not defined in the translation file, it should return the string itself, as per the [doc](https://www.i18next.com/principles/fallback).

```js
"Undefined variable: $example"
```

## Your Environment

- *runtime version*: node v.14.0
- *i18next version*:  20.3.3
- *os*: Mac

**Comment by jamuhl** [comment]
`:` is reserved as namespace separator -> https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces

Either override nsSeparator or pass a real defaultValue like: `i18next.t('Undefined variable: $example', 'Undefined variable: $example')`
