### ISSUE TITLE
How to use Interpolation in html attributes tag

### ISSUE THREAD

**Issue by sadashivm** [i18next/i18next-gitbook#175]
I'm using this library using npm module like,
npm install i18next
npm install loc-i18next

the above npm packages have installed in my react application but I dont want to use "npm i react-i18next".

Here is the sample code,

1. LocalizationExample.js
![image](https://user-images.githubusercontent.com/10355473/130639516-954c0a17-13f7-413d-95b0-66c7e15e085e.png)
![image](https://user-images.githubusercontent.com/10355473/130639599-5959ec11-275f-4b1d-95b4-921f336e0c19.png)

2.  en.json
![image](https://user-images.githubusercontent.com/10355473/130639729-65e0e1e9-80da-4afb-b537-0773b07eb568.png)

3. de.js
![image](https://user-images.githubusercontent.com/10355473/130639802-e863cd0f-4e21-4fc5-9b18-b284127c34de.png)

Can you please tell me, how to pass **username** value to key_3 paramater?

**Comment by jamuhl** [comment]
but why not using react-i18next with react (how it is meant to be)

**Comment by sadashivm** [comment]
Hi Jamuhl,
Thanks for reply!
I checked the above reference link, still it is not working and I want to this plugin in clojure application hence I'm not using react-i18next.

Here is the my code,
![image](https://user-images.githubusercontent.com/10355473/130766421-e92e96f0-a33e-46ff-ad9d-bb67ffdc2c22.png)
![image](https://user-images.githubusercontent.com/10355473/130766518-fdb554bb-d9fb-4883-b834-65b11a2d5e39.png)

and output is,

![image](https://user-images.githubusercontent.com/10355473/130766640-964e2d4c-beb2-4abb-afee-c89540e567c8.png)

**Comment by jamuhl** [comment]
please create a sandbox sample for easier recreation of the problem...my current guess is that your `i18n-options` are not correctly formatted and can't be parsed as JSON -> but you would have to check / debug it -> or provide a sample so I can have a look

**Comment by sadashivm** [comment]
Hi jamuhl,
please check below sandbox example,
https://codesandbox.io/s/zen-visvesvaraya-rythp?file=/src/App.js

**Comment by jamuhl** [comment]
like shown here: 

the options attribute as default is disabled: https://github.com/mthh/loc-i18next#initialize-the-plugin

changing useOptionsAttr: true in your code does the trick:

```js
function updateContent() {
  const localize = locI18next.init(i18next, {
    // optionsAttr: "data-i18n-options",
    useOptionsAttr: true
  });
  localize("html");
}
```
