### ISSUE TITLE
Language change can be reflected to URL route?

### ISSUE THREAD

**Issue by sjb3** [i18next/i18next-gitbook#184]
Hi, i18n,

While browsing the gitHub, I just learned that gitHub now supports many different languages.
Also, per selecting the language in dropdown, the URL also gets updated with corresponding country code! (not the contents though).
Wonder how can it be achieved with i18thnext (or is gitHub already using your library?).
I did a bit of testing/implementing but no success so far, if there's a way it will be AWESOME(care to share how to) otherwise it can be a good proposal for future development?

Cheers,

sjb3

**Comment by jamuhl** [comment]
There are two parts to that problem.

1) you build or use a UI framework (eg. next.js) / server that supports routing with language codes 
2) the i18n lib needs to get the language code from route (or server side) - this can be done using the language-detector

**Comment by jamuhl** [comment]
have a look at https://github.com/isaachinman/next-i18next

**Comment by sjb3** [comment]
Hi Jan,

Thanx for the quick response and resources!
Currently, as we're using aws serverless for backend, no plan to add/migrate to nextJS but will stay with reactJS.

After checking the nextJS, is there any other way that(from frontend) that we can change the route or path?

Thanx in advances!

Justin

________________________________

**Comment by sjb3** [comment]
I kind of came up with this temporary solution.

`<Router basename={`/TEMP/${currentLanguageCode}`} forceRefresh>`
It's sort of working on local but the changes are not immediately reflected, hence added forceRefresh, to get it updated i will need to click tabs a few more.

Mostly upsetting thing is, on our internal dev server, forceRefresh in the directive is not applicable.

Any ideas?

Just

**Comment by jamuhl** [comment]
No sorry...personally I never had the demand to have a clientside solution do this. It's a problem that needs to be somewhat solved in whatever router solution you're using...guessing it's react-router...
