### ISSUE TITLE
404 and Broken link!

### ISSUE THREAD

**Issue by BaseMax** [i18next/i18next-gitbook#207]
Inside https://www.i18next.com/ page:

There is a broken link `https://locize.com/blog/how-does-server-side-internationalization-look-like/jq`

```
<a href="https://locize.com/blog/how-does-server-side-internationalization-look-like/jq" data-rnwi-5xr8s6-dse9kg-2fw26.....
````

**Comment by adrai** [comment]
Thank you...
Should be fixed now: https://locize.com/blog/how-does-server-side-internationalization-look-like/
