### ISSUE TITLE
Add dark mode?

### ISSUE THREAD

**Issue by TheAlan404** [i18next/i18next-gitbook#217]
## 🚀 Feature Proposal

Adding dark mode to the documentation pages.

## Motivation

Some users might find dark mode more convenient since it is easier to read for most people and consumes less battery. It would also make sense if the user's every other documentation page is in dark mode.

## Example

N/A

**Comment by adrai** [comment]
just enabled that on gitbook... you should be able to toggle it
<img width="1498" alt="image" src="https://github.com/i18next/i18next-gitbook/assets/1086194/cdcf6a0e-9de8-42d6-8a52-480a44729c6c">
