### ISSUE TITLE
Selection on docs website is broken

### ISSUE THREAD

**Issue by Seasle** [i18next/i18next-gitbook#230]
## 🐛 Bug Report

On the website with documentation the mouse selection does not work, or rather it is not visible. I would like it to work correctly.

## To Reproduce

Just open the [website](https://www.i18next.com) (except for the Introduction page) and try to highlight something. Had a quick look at the cause, and the `--scalar-selection-background` and `--scalar-selection-color` variables are missing on `::selection`.

**Comment by Seasle** [comment]
Originally found this on a website on react-i18next and decided on the main website to check it out.
i18next/react-i18next-gitbook#149

**Comment by adrai** [comment]
will close, since there's not much we can do here
