### ISSUE TITLE
Minor typo in docs

### ISSUE THREAD

**Issue by minitauros** [i18next/i18next-gitbook#33]
Just a notification, took me some time but then I got it working ;)

https://www.i18next.com/add-or-load-translations.html#

In the "Add after init" part, there's a single quote missing in the example. Just notifying you guys in case you have as much OCD as me.

    // Missing a single quote after 'en
    i18next.addResourceBundle('en, 'namespace1', {
	  key: 'hello from namespace 1'
	});

**Comment by jamuhl** [comment]
thank you...publishing an update right now.
