### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by gatispriede** [i18next/i18next-gitbook#47]
I suggest to fix loadNamespaces to return `t` as specific namespace translations.

Also would be nice to add fallback translations to load from default:

Snippet im using currently:

i```
mport i18n from 'translations/i18n'; //initialized i18n
i18n.loadNamespaces('NAMESPACE');

const t = translationString => {
    //try common namespace
    const nsTranslation = i18n.t('NAMESPACE:' + translationString);
    if(translationString === nsTranslation){
        return i18n.t(translationString);
    }
    //else return namespaced translation
    else{
        return nsTranslation;
    }
};

```
//t gets passed down as props to react components

**Comment by jamuhl** [comment]
honestly i don't get what you do.

Just pass namespaces needed as array in init options `i18next.init({ ns: ['ns1', 'ns2', 'ns3'] });`.

For fallback namespace you can define fallbackNS: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

Using i18next.getFixedT could be used to get a `t` function fixed to your additional namespace https://www.i18next.com/overview/api#getfixedt

and for react...https://github.com/i18next/react-i18next might give you more than just passing down `t` (wait for languages loaded, pass down `t` fixed to given namespace, components to translate node tree -> interpolate eg. Link component into translations)

**Comment by jamuhl** [comment]
i18n.loadNamespaces has a callback -> what is it's function -> load a namespace and callback when translations were loaded and ready to use:

```js
i18next.loadNamepaces('ns1', () => {
   const fixedT = i18next.getFixedT(null, 'ns1');
});
```

**Comment by gatispriede** [comment]
Looks like i missed: i18next.getFixedT function,
is loadNamepaces async call?

**Comment by jamuhl** [comment]
loadNamespace is async if backend is async -> you load them using eg. xhr-backend

fallback es-ES -> es -> fallbackLng is default...just read: https://www.i18next.com/principles/fallback#language-fallback

**Comment by jamuhl** [comment]
you're welcome - hope you now have your solution setup - if not just ask if something else needs to be clearified.
