### ISSUE TITLE
Unclear fallback order

### ISSUE THREAD

**Issue by chiefraccoon** [i18next/i18next-gitbook#49]
Please, specify, what behavior we will get if set both "language fallback" and "namespace fallback"?

**Comment by chiefraccoon** [comment]
it seems logical, but i am asking because, we have faced with opposite behaviour:

eg. lng `ru-Ru` fallback `en-Gb`; namespace `custom-translations` fallback `default-translations`,
providing key that is specified in  `ru-Ru` - `default-translations`;

1. don't find it in ru-RU-custom
2. (don't find it in ru-custom)
3. don't find it in en-GB-custom
4. find it in ru-RU-default
5. ...

So it attempts to lookup key within one namespace, using fallback lang, and only then goes to another namespace. 

Here is debug session record:
https://i.gyazo.com/621441f9c15af796616f80ce7fd9d348.mp4

And here is config:
```javascript
this.i18nextInstance = i18next.use(reactI18nextModule).init({
            resources: {
                'en-GB': {
                    [TRANSLATION_NAME_SPACES.DEFAULT]: initialTranslations
                }
            },
            fallbackLng: 'en-GB',
            ns: [TRANSLATION_NAME_SPACES.CUSTOM, TRANSLATION_NAME_SPACES.DEFAULT],
            fallbackNS: [TRANSLATION_NAME_SPACES.CUSTOM, TRANSLATION_NAME_SPACES.DEFAULT],
            defaultNS: TRANSLATION_NAME_SPACES.CUSTOM,
            debug: false,
            react: {
                wait: true,
                nsMode: 'fallback'
            },
            saveMissing: true,
            missingKeyHandler: (...args) => {
                // need to disable linter, to emphasize missing key message in console
                // tslint:disable-next-line
                console.error('MISSING KEY', args);
            }
        });
```
version of i18next - 11.3.6

**Comment by jamuhl** [comment]
Currently on a short trip vacation. Will have a look when back. Later thos week. 

Von meinem iPhone gesendet

**Comment by jamuhl** [comment]
you're right it will be:

1) don't find it in de-app
2) don't find it in en-app
3) don't find it in de-common
4) don't find it in en-common
5) you had 4 chances to provide the translation -> we just show the key now...

namespace has prio over https://github.com/i18next/i18next/blob/master/src/Translator.js#L239 language code https://github.com/i18next/i18next/blob/master/src/Translator.js#L243

**Comment by chiefraccoon** [comment]
It seems it's not what the majority expect, even you described more logical behavior at first.
The current one changes the language two times... which is confusing.
Could you consider to make this behavior configurable? And it would be better to describe how it is now in doc though.

**Comment by jamuhl** [comment]
guess it makes no difference...if stuff is not specified in a namespace that should be consistent for all languages

so current:

1) don't find it in de-app
2) don't find it in en-app
3) find it in de-common

will be same result as:

1) don't find it in de-app
2) find it in de-common

**Comment by kevin-lindsay-1** [comment]
@chiefraccoon I just had a PR merged that I believe should solve this issue for you.
https://github.com/i18next/i18next-gitbook/pull/56

**Comment by jamuhl** [comment]
closing this for now...as documentation was improved to be more specific on this one.
