### ISSUE TITLE
I18next undefinied

### ISSUE THREAD

**Issue by gintnerviktor** [i18next/i18next-gitbook#76]
Unfortunately, at today afternoon the plugin doesn’t work at all. Maybe you updated it... The plugin downloaded, but i always get an i18next undefined message. Earlier, the website worked fine with i18next. Besides this, your examples in your i18next.com don’t work too. Could you check it? Thanks, viktor

**Comment by jamuhl** [comment]
can you give some more details? what plugin is not working?

**Comment by gintnerviktor** [comment]
Hi there! Thanx for your quick replay! Here is a simple wedding website, what earlier worked perfectly, https://esztijani.com . On the javascript console you can see the error message.

**Comment by jamuhl** [comment]
try fixing i18next to v14 -> https://unpkg.com/i18next@14.1.1/i18next.js

or replace i18next with window.i18next

**Comment by jamuhl** [comment]
will need to investigate further

**Comment by jamuhl** [comment]
ah found it...give me a minute

**Comment by jamuhl** [comment]
https://unpkg.com/i18next@15.0.1/i18next.js will fix this...not yet sure how long it takes the CDN to serve that as primary

**Comment by gintnerviktor** [comment]
Hi there! Thank you so much!!! With the tag @15.0.1  works everything fine!!!  Have a nice day!
