### ISSUE TITLE
Construct 3 plugin

### ISSUE THREAD

**Issue by nagyv** [i18next/i18next-gitbook#80]
Hi,

I've created a simple Construct 3 plugin to use i18next in Construct 3. How could I get the the plugin listed in the docs?

You can find the plugin's repo here: https://github.com/nagyv/c3-i18next/

Moreover, I would like to ask you if you permit the use of your logo the way I did. It mixes C3 logo with yours in an extremely simple way. (I'm not a designer. :)) You can check the logo here: https://www.construct.net/en/make-games/addons/249/c3-i18next

**Comment by jamuhl** [comment]
@nagyv sure you can use the logo and modify it to your need if in relation to using i18next

Added c3 here: https://www.i18next.com/overview/supported-frameworks directly after phaser (as the list gets longer and longer i might to have to sort it proper some day)
