### ISSUE TITLE
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by J-eno** [i18next/i18next-gitbook#84]
I tried importing i18next and the backend into my project after installing it from npm, but when I run my project on a local server, I keep getting: Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
![image](https://user-images.githubusercontent.com/24687137/55850383-1d4b4a80-5b22-11e9-8dae-1d443781a363.png)

**Comment by jamuhl** [comment]
are you bundling using webpack...or trying a setup with browser modules directly?!?

**Comment by J-eno** [comment]
I haven't bundled anything. If I'm being honest, I don't know what I'm doing.

**Comment by jamuhl** [comment]
so what you expect me todo?

**Comment by J-eno** [comment]
This is your library, correct? I'm trying to see if you've seen this error before. I set it up the same way I saw it in the documentation. Am I missing something? Am I meant to bundle it using a webpack?

**Comment by jamuhl** [comment]
the samples there (https://www.i18next.com/overview/getting-started#basic-sample) are with "modern web" in mind (and you should see that if somewhat familiar with web development)

every sample there has a old school fiddle like: https://jsfiddle.net/jamuhl/dvk0e8a9/#tabs=js,result,html

**Comment by jamuhl** [comment]
So no - never saw that - seems your doing either something very new or something very wrong 😁

**Comment by J-eno** [comment]
Yeah, I followed every sample I saw on the documentation, but the browser keeps having problems with my 'import backend' line. I'm going to bet I'm doing something very wrong 😂

**Comment by jamuhl** [comment]
you can't import like that...that only works using webpack or similar module bundler: https://webpack.js.org/ (so react, angular, vue or similar - but not just plain browser)

**Comment by J-eno** [comment]
It worked after I bundled it. Thanks a lot! If I'm getting new errors ($(...).i18n is not a function) should I open a new thread and close this one?

**Comment by jamuhl** [comment]
I would suggest asking implementation / general how to questions over at stackoverflow...github issues are meant for issues were a module has a bug or you request a new feature. It's not a place to ask for implementation guidance or development assistance (as much i would like to help everyone maintaining OSS is taking a lot of unpaid time which means time from my family - so i can't do free support / teaching - hope that is understandable)

**Comment by J-eno** [comment]
I understand completely. You've been very helpful man. Thank you and enjoy your day.

**Comment by riteshmaurya** [comment]
i am also receivig this issue when providing deployUrl in build

**Comment by sc-varraj** [comment]
Failed to load angular build dist folder js files getting mime type error..

**Comment by sc-varraj** [comment]
- 
![Uploading Screenshot (43).png…]()
