### ISSUE TITLE
cdn url stop working

### ISSUE THREAD

**Issue by onneri** [i18next/i18next-gitbook#89]
this resource "https://unpkg.com/i18next/i18next.min.js" stop working
are you guys planning on redirect it to the new cdn url?

**Comment by jamuhl** [comment]
brought back in i18next@17.0.2

but be aware any update when using https://unpkg.com/i18next/i18next.min.js could be breaking as it redirects to lastest version (which could be major and API breaking)

you should use a fixed version like https://unpkg.com/i18next@16.0.0/i18next.min.js to make sure there is nothing breaking when using latest

**Comment by onneri** [comment]
awesome, I don't know where did I get that url in first place, because in your docs are the .../dist/.. ones.
thank you @jamuhl appreciate the info
