### ISSUE TITLE
Utility to get the correct plural suffixes doesn't work now

### ISSUE THREAD

**Issue by Lehakos** [i18next/i18next-gitbook#90]
https://jsfiddle.net/jamuhl/3sL01fn0/#tabs=result - error in console: `Uncaught TypeError: i18next.init is not a function`

**Comment by jamuhl** [comment]
should be fixed in i18next@17.0.3

**Comment by Dcyperion888** [comment]
😎

**Comment by Dcyperion888** [comment]
Who's the "real" 🔑
